services:
  - type: web
    name: artha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13